import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from '../dist/worker.js';
import {seal,open,fetchJSON} from '../src/security.js';
import {loginZepp,validate} from '../src/zepp.js';
const origin='https://mimotion.test';
const time=()=>Math.floor(Date.now()/1000);
const day=()=>new Date(Date.now()+28800000).toISOString().slice(0,10);
function environment(){
 const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON');for(const file of ['0001_multiuser.sql','0002_delivery.sql'])db.exec(readFileSync(new URL('../migrations/'+file,import.meta.url),'utf8'));
 const env={APP_ORIGIN:origin,MASTER_SECRET:'test-secret-only',MAX_ACCOUNTS:'200',db,sent:[],queries:0};
 function statement(sql,args=[]){return {bind(...v){return statement(sql,v);},async first(){env.queries++;return db.prepare(sql).get(...args)||null;},async all(){env.queries++;return {results:db.prepare(sql).all(...args)};},async run(){env.queries++;const r=db.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}};}};}
 env.DB={prepare:sql=>statement(sql),batch:async statements=>{db.exec('BEGIN');try{const r=await Promise.all(statements.map(s=>s.run()));db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}};
 env.JOBS={send:async body=>env.sent.push(body),sendBatch:async items=>env.sent.push(...items.map(i=>i.body))};return env;
}
function req(path,data,cookie='',csrf='test-csrf',headers={}){return new Request(origin+path,{method:data===undefined?'GET':'POST',headers:{Cookie:cookie,Origin:origin,'Content-Type':'application/json','X-CSRF-Token':csrf,...headers},...(data===undefined?{}:{body:JSON.stringify(data)})});}
async function api(env,path,data,a={}){return worker.fetch(req(path,data,a.cookie,a.csrf),env);}
async function account(env,id,enabled=1){const tokens={user_id:id,login_token:'login-'+id,app_token:'app-'+id,bound_device_id:'ABCDEF123456'};env.db.prepare('INSERT INTO accounts(id,label,credentials,enabled,session_version,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(id,id+'***',await seal(tokens,env.MASTER_SECRET,'zepp:'+id),enabled,'version',time(),time());const s={id,version:'version',csrf:'test-csrf',exp:time()+600};return {id,csrf:s.csrf,cookie:'__Host-mimotion-user-v2='+await seal(s,env.MASTER_SECRET,'user-session-v2')};}
function addRun(env,id,owner,kind='manual',status='queued',d=day()){env.db.prepare('INSERT INTO runs(id,account_id,slot,kind,day,step,status,created_at,updated_at) VALUES(?,?,?,?,?,20000,?,?,?)').run(id,owner,id,kind,d,status,time(),time());}
function msg(id,attempts=1){return {body:{id},attempts,acked:false,retried:false,ack(){this.acked=true;},retry(){this.retried=true;}};}
function consume(env,m){return worker.queue({messages:[m]},env);}
function zeppMock(t,options={}){const calls=[];let active=0,maxActive=0;
 t.mock.method(globalThis,'fetch',async(url,opts={})=>{url=String(url);calls.push({url,opts});
 if(url.includes('/registrations/tokens'))return new Response(null,{status:303,headers:{Location:'https://example.test/?access=valid-access'}});
 if(url.includes('/v2/client/login')){assert.equal(new Headers(opts.headers).has('x-hm-ekv'),false);return Response.json({result:'ok',token_info:{login_token:'login-token',app_token:'app-token',user_id:options.userId||'verified-user'}});}
 if(url.includes('/device/binds.json'))return Response.json({items:[]});
 if(url.includes('/client/app_tokens')){if(options.expired)return Response.json({result:'fail'},{status:401});return Response.json({result:'ok',token_info:{app_token:'refreshed-'+new URL(url).searchParams.get('login_token')}});}
 if(url.includes('/band_data.json')){active++;maxActive=Math.max(active,maxActive);await new Promise(r=>setTimeout(r,15));active--;if(options.timeout)throw new Error('private-token-upstream');return Response.json({message:'success'});}
 throw new Error('Unexpected fetch');});return {calls,get maxActive(){return maxActive;}};}

test('public page, legacy sessions, origin and CSRF protection',async()=>{const env=environment();assert.match(await (await api(env,'/')).text(),/首次验证成功/);assert.equal((await api(env,'/api/run',{})).status,401);const a=await account(env,'A');assert.equal((await worker.fetch(req('/api/settings',{},a.cookie,'bad'),env)).status,403);assert.equal((await worker.fetch(req('/api/login',{},'', '',{Origin:'https://evil.test'}),env)).status,403);assert.equal((await api(env,'/api/config/save',{},a)).status,404);assert.equal((await api(env,'/api/run',{}, {cookie:'__Host-mimotion-session=old'})).status,401);});

test('Zepp direct login creates isolated encrypted account without password; re-login revokes old cookie',async(t)=>{const env=environment();zeppMock(t);const input={account:'test@example.com',password:'secret#password',min_step:18000,max_step:25000,consent:true};const r=await api(env,'/api/login',input);assert.equal(r.status,200);const c=r.headers.get('set-cookie').split(';')[0];assert.match(r.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Strict/);const status=await (await api(env,'/api/status',undefined,{cookie:c})).json();assert.equal(status.signed_in,true);assert.equal(status.account.enabled,false);const row=env.db.prepare('SELECT * FROM accounts').get();const stored=JSON.stringify(row);assert.ok(!stored.includes(input.password));assert.ok(!stored.includes('login-token'));assert.ok(!stored.includes(input.account));assert.equal((await open(row.credentials,env.MASTER_SECRET,'zepp:'+row.id)).user_id,'verified-user');await assert.rejects(open(row.credentials,env.MASTER_SECRET,'zepp:someone-else'));await api(env,'/api/login',input);assert.equal((await (await api(env,'/api/status',undefined,{cookie:c})).json()).signed_in,false);assert.equal(env.db.prepare('SELECT COUNT(*) AS n FROM accounts').get().n,1);});

test('two users can run concurrently with their own tokens and cannot read/change/delete each other',async(t)=>{const env=environment(), a=await account(env,'A'),b=await account(env,'B');const mock=zeppMock(t);addRun(env,'run-a','A');addRun(env,'run-b','B');await Promise.all([consume(env,msg('run-a')),consume(env,msg('run-b'))]);assert.equal(mock.maxActive,2);const submits=mock.calls.filter(c=>c.url.includes('/band_data.json'));assert.equal(submits.length,2);for(const call of submits){const p=call.opts.body;const uid=p.get('userid');assert.equal(call.opts.headers.apptoken,'refreshed-login-'+uid);assert.equal(p.get('last_deviceid'),'ABCDEF123456');const payload=JSON.parse(p.get('data_json'))[0];assert.equal(payload.date,day());assert.equal(JSON.parse(payload.summary).stp.ttl,20000);}
 const ar=await (await api(env,'/api/runs?account_id=B',undefined,a)).json();assert.deepEqual(ar.runs.map(r=>r.id),['run-a']);assert.equal((await api(env,'/api/settings',{account_id:'B',min_step:1,max_step:2,enabled:false},a)).status,200);assert.equal(env.db.prepare("SELECT enabled FROM accounts WHERE id='B'").get().enabled,1);assert.equal((await api(env,'/api/delete',{confirm:'DELETE',account_id:'B'},a)).status,200);assert.equal(env.db.prepare('SELECT COUNT(*) AS n FROM runs').get().n,1);assert.equal((await api(env,'/api/runs',undefined,a)).status,401);assert.equal((await api(env,'/api/runs',undefined,b)).status,200);});

test('same account and duplicate deliveries never submit concurrently or repeat success',async(t)=>{const env=environment();await account(env,'A');addRun(env,'one','A');addRun(env,'two','A');const mock=zeppMock(t), m=msg('two');await Promise.all([consume(env,msg('one')),consume(env,msg('one')),consume(env,m)]);assert.equal(mock.maxActive,1);assert.equal(mock.calls.filter(c=>c.url.includes('/band_data')).length,1);assert.equal(m.retried,true);await consume(env,msg('one'));assert.equal(mock.calls.filter(c=>c.url.includes('/band_data')).length,1);await consume(env,msg('two',2));assert.equal(mock.calls.filter(c=>c.url.includes('/band_data')).length,2);});

test('uncertain POST is visible and never automatically resubmitted',async(t)=>{const env=environment();await account(env,'A');addRun(env,'r','A');const mock=zeppMock(t,{timeout:true});await consume(env,msg('r'));await consume(env,msg('r',2));const row=env.db.prepare('SELECT * FROM runs').get();assert.equal(row.status,'unknown');assert.ok(!row.message.includes('private-token'));assert.equal(mock.calls.filter(c=>c.url.includes('/band_data')).length,1);assert.equal(env.db.prepare('SELECT lease_until FROM accounts').get().lease_until,0);});

test('expired credentials pause the user; paused and previous-day jobs do not submit',async(t)=>{const env=environment();await account(env,'A');addRun(env,'r','A');const mock=zeppMock(t,{expired:true});await consume(env,msg('r'));assert.equal(env.db.prepare('SELECT enabled FROM accounts').get().enabled,0);assert.equal(env.db.prepare('SELECT needs_login FROM accounts').get().needs_login,1);addRun(env,'s','A','schedule');addRun(env,'old','A','manual','queued','2001-01-01');await consume(env,msg('s'));await consume(env,msg('old'));assert.equal(mock.calls.filter(c=>c.url.includes('/band_data')).length,0);assert.deepEqual(env.db.prepare('SELECT status FROM runs ORDER BY id').all().map(r=>r.status),['skipped','failed','skipped']);});

test('scheduler batches 200 accounts within query budget, retries outbox, and deduplicates slots',async()=>{const env=environment();for(let i=0;i<200;i++)await account(env,'u'+i);env.queries=0;const tick={scheduledTime:Date.parse(day()+'T00:35:00Z')};await worker.scheduled(tick,env);assert.equal(env.db.prepare('SELECT COUNT(*) AS n FROM runs').get().n,200);assert.equal(env.sent.length,200);assert.ok(env.queries<30);env.sent=[];await worker.scheduled(tick,env);assert.equal(env.sent.length,0);assert.equal(env.db.prepare('SELECT COUNT(*) AS n FROM runs').get().n,200);
 env.db.prepare("UPDATE runs SET status='pending'").run();env.JOBS.sendBatch=async()=>{throw new Error('queue unavailable');};await worker.scheduled({scheduledTime:tick.scheduledTime+300000},env);assert.equal(env.db.prepare("SELECT COUNT(*) AS n FROM runs WHERE status='pending'").get().n,200);env.JOBS.sendBatch=async items=>env.sent.push(...items);await worker.scheduled({scheduledTime:tick.scheduledTime+600000},env);assert.equal(env.sent.length,200);});

test('login and manual run rate limits do not create extra jobs',async(t)=>{const env=environment();const a=await account(env,'A');assert.equal((await api(env,'/api/run',{},a)).status,202);assert.equal((await api(env,'/api/run',{},a)).status,429);assert.equal(env.db.prepare('SELECT COUNT(*) AS n FROM runs').get().n,1);zeppMock(t);const data={account:'a@example.com',password:'p',min_step:1,max_step:2,consent:true};for(let i=0;i<5;i++)assert.equal((await api(env,'/api/login',data)).status,200);assert.equal((await api(env,'/api/login',data)).status,429);});

test('non-JSON failures never expose upstream bodies; invalid inputs rejected',async(t)=>{t.mock.method(globalThis,'fetch',async()=>new Response('secret-upstream-token',{status:502,headers:{'content-type':'application/octet-stream'}}));await assert.rejects(fetchJSON('https://example.test'),e=>e.message.includes('二进制')&&!e.message.includes('secret-upstream'));assert.equal(validate({account:'13800138000',password:'a#b',min_step:1,max_step:2}).account,'+8613800138000');assert.throws(()=>validate({account:'a@example.com',password:'p',min_step:4,max_step:2}));});
